# Makefile for fileReverse.c with macros

FLAGS   = -std=c99 -Wall
SOURCES = charType.c
OBJECTS = charType.o
EXEBIN  = charType
INFILE= infile
OUTFILE= outfile

all: $(EXEBIN)

$(EXEBIN) : $(OBJECTS)
	gcc -o $(EXEBIN) $(OBJECTS)

$(OBJECTS) : $(SOURCES)
	gcc -c $(FLAGS) $(SOURCES)
	
clean:
	rm -f $(EXEBIN) $(OBJECTS)

check:
valgrind --leak-check=full charType charType.c infile outfile
